repos:
 - repo: https://github.com/astral-sh/ruff-pre-commit
   # Ruff version.
   rev: "v0.3.7"
   hooks:
     # Run the linter.
     - id: ruff
       always_run: true
     # Run the formatter.
     - id: ruff-format
       always_run: true
 - repo: https://github.com/RobertCraigie/pyright-python
   rev: v1.1.362
   hooks:
   - id: pyright
     always_run: true
     # Need to add those three lines because pyright is buggy at config point Oo
     additional_dependencies:
       - -r
       - /home/koko/projects/PFMG/requirements-dev.txt
 # Same thing that for pyright...
 # all this section is wordy because
 # they did not provide a simplest way to do it.
 - repo: local
   hooks:
     - id: pytest
       name: pytest
       entry: /home/koko/.pyenv/versions/3.12.0/envs/PFMG/bin/pytest
       args: [-vvv, --showlocals]
       language: python
       pass_filenames: false
       always_run: true
