repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.4"
    hooks:
      - id: ruff
        always_run: true
        stages:
          - pre-commit
      - id: ruff-format
        always_run: true
        stages:
          - pre-commit
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        language: python
        always_run: true
        entry: poetry run pyright
        stages:
          - pre-commit
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: python
        pass_filenames: false
        always_run: true
        stages:
          - pre-commit
  - repo: local
    hooks:
      - id: copyright
        name: copyright
        language: script
        always_run: true
        entry: ./bin/apply_licence.sh
        stages:
          - pre-commit
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
