[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "test",
    "tests",
    "__init__.py"
]

# Same as Black.
line-length = 80
indent-width = 4

# Assume Python 3.11
target-version = "py311"

output-format = "grouped"

[tool.ruff.lint]
select = [
    "A",
    "ANN001",
    "ASYNC",
    "B",
    "BLE",
    "C901",
    "COM",
    #    "CPY",
    "C4",
    "D",
    "DTZ",
    "E4", "E7", "E9",
    "EM",
    "EXE",
    "F",
    "FA",
    "FBT",
    #    "FIX",
    "I",
    "ICN",
    "INP",
    "ISC",
    "N",
    "PIE",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SLF",
    "TRIO",
    "T20",
    "UP",
    "YTT",
]
ignore = [
    "D203",
    "D213",
    "D401",
    "N803",
    "N999",
    "ANN101",  # Deprecated rule
    "ANN102",  # Deprecated rule
    "S101",
    "S506"
]

# Allow fix for all enabled rules (when `--fix`) is provided.
#fixable = ["ALL"]
unfixable = ["B"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Ignore `F401` (import violations) in all `__init__.py` files, and in select subdirectories.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
#"**/{tests,docs,tools}/*" = ["F401"]

[tool.ruff.lint.flake8-builtins]
builtins-ignorelist = ["object"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
