# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"
      - uses: Gr1N/setup-poetry@v9
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: "${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}"
      - name: Configure poetry
        run: |
          poetry install
      - name: Linter
        run: |
          poetry ruff check
      - name: Type Checker
        run: |
          poetry pyright
      - name: Test with pytest
        run: |
          poetry pytest --cov
        shell: bash
